### PR TITLE
prevent nuking a tag that has children

### LINKED ISSUE #2025: Deleting a tag that has children causes a DB error
If you try to delete a tag that has children, you might expect that to work, with the children being reparented up the chain.  Or you might expect some sort of "what do you want to do about the children?" UI.  What you actually get, though, is a server error, which turns out to be a DB validation error:

```
ActiveRecord::InvalidForeignKey (Mysql2::Error: Cannot delete or update a parent row: a foreign key constraint fails (`qpixel_dev`.`tags`, CONSTRAINT `fk_rails_aff1790b59` FOREIGN KEY (`parent_id`) REFERENCES `tags` (`id`))):

Causes:
Mysql2::Error (Cannot delete or update a parent row: a foreign key constraint fails (`qpixel_dev`.`tags`, CONSTRAINT `fk_rails_aff1790b59` FOREIGN KEY (`parent_id`) REFERENCES `tags` (`id`)))
```

### PR DESCRIPTION
**Pull request by cellio**
If a tag has children, replace the nuke page with its warnings and "are you sure?" button with a message saying you need to handle the children first.  I opted for a simple message rather than disabling the button because with that whole page full of red boxes, doing that felt like burying the lede.

While it shouldn't be possible to reach the `nuke` method in the controller, I also added a check there just in case.

Minimally fixes https://github.com/codidact/qpixel/issues/2025.  A more advanced fix would be to do something reasonable with the children, but that requires some design discussion as I'm not sure we want to simply reparent them.  Maybe we want a human to decide.  In the meantime, this at least prevents the server error.

### CODE REVIEW

**Comment by cellio** [comment]
I see the codecov complaint.  I don't know what it means in the context of this PR or what I should do about it.

File: app/controllers/tags_controller.rb [hunk 1]
```diff
@@ -225,31 +225,36 @@ def merge
...
+        end
+
+        # Nuke it
+        @tag.destroy
       end
 
-      # Nuke it
-      @tag.destroy
+      flash[:success] = "Deleted #{@tag.name}"
+      redirect_to category_tags_path(@category)
```
Comment (ArtOfCode-) [inline app/controllers/tags_controller.rb]: Unless an explicit `render` or `redirect` call is made, Rails' default behaviour is to render a view with the same name as the action (i.e. `app/views/tags/nuke.html.erb`). Since you've moved this `redirect` call into the `else` path, the `if` path for when a tag has children doesn't render or redirect, so this is what it will try to do. As that view doesn't exist, it will 404.

Easiest fix is to move the `redirect` call back outside the `if`/`else` block, leaving the `flash` inside it.

File: app/views/tags/nuke_warning.html.erb [hunk 2]
```diff
@@ -6,6 +6,10 @@
 
 <h1>Delete tag <%= @tag.name %></h1>
 
+<% if @tag.children.any? %>
+<p><strong>Tags with children cannot be deleted. Please reparent the children first.</strong></p>
```
Comment (ArtOfCode-) [inline app/views/tags/nuke_warning.html.erb]: I'd suggest a warning notice here rather than a plain paragraph - take an example from the `else` block:


```suggestion
<div class="notice is-warning has-color-yellow-900">
  <p>
    <strong>Tags with children cannot be deleted. Please reparent the children first.</strong>
  </p>
</div>
```

**Review by ArtOfCode- — CHANGES_REQUESTED** [review]

File: app/views/tags/nuke_warning.html.erb (hunk 2 above)
Comment (cellio) [reply app/views/tags/nuke_warning.html.erb]: Much better, thanks.

**Review by ArtOfCode- — APPROVED** [review]
